import { PlusIcon } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ManagementCard, ManagementPage, Note, PageHeading } from "./shared";

export function CreateOrderView() {
  const items = [
    ["Mechanical Keyboard", "KB-001 · RM 199.00", "1", "RM 199.00"],
    ["Wireless Mouse", "MS-014 · RM 89.00", "2", "RM 178.00"],
  ];
  return (
    <ManagementPage>
      <PageHeading
        title="Create order"
        description="Build a new customer order. Prices and totals are generated by the server."
        action={
          <div className="flex gap-2">
            <Button nativeButton={false} variant="outline" render={<Link href="/orders" />}>
              Cancel
            </Button>
            <Button>Create order</Button>
          </div>
        }
      />
      <div className="grid gap-3 lg:grid-cols-[1.5fr_1fr]">
        <ManagementCard title="Order details">
          <div className="flex flex-col gap-5">
            <label className="flex flex-col gap-2 text-sm">
              Customer
              <select className="h-9 rounded-lg border bg-background px-3">
                <option>Search active customers…</option>
                <option>John Tan</option>
              </select>
            </label>
            <div>
              <div className="mb-2 flex justify-between">
                <h3 className="text-sm font-medium">Order items</h3>
                <Button variant="outline" size="sm">
                  <PlusIcon data-icon="inline-start" />
                  Add product
                </Button>
              </div>
              {items.map((item) => (
                <div
                  className="grid grid-cols-[1fr_4rem_auto] items-center gap-3 border-b py-3 text-sm"
                  key={item[0]}
                >
                  <b>
                    {item[0]}
                    <br />
                    <small className="text-muted-foreground">{item[1]}</small>
                  </b>
                  <Input defaultValue={item[2]} aria-label="Quantity" />
                  <b>{item[3]}</b>
                </div>
              ))}
            </div>
            <label className="flex flex-col gap-2 text-sm">
              Shipping address
              <textarea
                className="min-h-20 rounded-lg border bg-background p-3"
                defaultValue="10 Jalan Example, 50450 Kuala Lumpur"
              />
            </label>
            <label className="flex flex-col gap-2 text-sm">
              Internal notes
              <textarea
                className="min-h-20 rounded-lg border bg-background p-3"
                placeholder="Optional fulfilment note"
              />
            </label>
          </div>
        </ManagementCard>
        <ManagementCard title="Order summary">
          <div className="flex flex-col gap-3 text-sm">
            <div className="flex justify-between">
              <span>3 items</span>
              <b>RM 377.00</b>
            </div>
            <div className="flex justify-between">
              <span>Shipping</span>
              <b>Included</b>
            </div>
            <div className="flex justify-between border-t pt-3 text-base">
              <b>Total</b>
              <b>RM 377.00</b>
            </div>
          </div>
          <Note>New orders begin as Pending. Products cannot appear twice in one order.</Note>
        </ManagementCard>
      </div>
    </ManagementPage>
  );
}
